# -*- coding: utf-8 -*-
"""notebook47f76929e8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/adithyaep/notebook47f76929e8.3e75557c-9a28-497d-b044-85dbcf5734a5.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251121/auto/storage/goog4_request%26X-Goog-Date%3D20251121T143823Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D6c16aa8c9289fefb02bbd29c927e5a3e7a7d6947a82789c976738b8b3c70ef276170c23d8b12f30a35b7c276f81316372a40248f1e88958316dc431ea4fbd409a908a85ccecbfef39caeab852b5ad43d405343067fc11f8bdea0e856e06deaf81f803dbe9d1d142a072a9f59b3238dc44681431f09ed43f4c2d6127718f03660af5f4b329aae5df1c531388fc3df7314ad2469475cae5dd8ce2092e9dc76349240e8261f6dfb7b6cb03e9a8283193de1fd6a6085e566144ba73eb300ff8b64553ee8c0f9863f499d9a1c76d7219a81f2bbef20a582ae6db8136135ba737568e12119a44b9127dc8efa311719e4e2dc338f7de8f77db343a065dfbfbe4866ffd3
"""

gitignore_text = """
# Byte-compiled
__pycache__/
*.pyc

# Virtual environments
venv/
.env/

# Notebook checkpoints
.ipynb_checkpoints/

# OS files
.DS_Store

# Outputs (avoid large artifacts)
outputs/
*.pdf
dac_agent_submission.zip

# Ignore local memory/storage
data/memory.json
"""

with open(".gitignore", "w") as f:
    f.write(gitignore_text)

print("✔ .gitignore created")