# -*- coding: utf-8 -*-
"""notebook47f76929e8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/adithyaep/notebook47f76929e8.17f0c328-e201-4d1a-a9af-289cf2f667d8.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20251121/auto/storage/goog4_request%26X-Goog-Date%3D20251121T143604Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D229b566c5ed43fca521890ca631a3464d3926c5e78999738d34fc3297f0e586bbc42143ca17e3f3184ad14d801caaea508b29e05af7b070afbb6945ddf72020663086686ffc0d5c07569ef753ce615a79bb105569481dff2933779347281b847a7f00d4c516b47635323ce88be1efdbb5309c24ad18703cb8b79393b2304501a107e08caa40a5f8ee88ec3b0a409d8ccf6205dd4f2ec11b6c0aaba37b2b7640ddf6c46f0c0effee7f72a88cd300b35a1d0adb9fef99fca8d8dcd520cae14729e306bb5f22f9dcf5981c855124c0e5b1fb727be12f216cfbf7790ba4ecbd7f51e07f0ddc15a75d44dc27bdb77a08ae52ce39fc41da73c902e49842f7abcae8458
"""

requirements = """
pandas
numpy
matplotlib
seaborn
python-dateutil
reportlab
"""

with open("requirements.txt", "w") as f:
    f.write(requirements)

print("✔ requirements.txt created")